name: stgat

target: src.models.stgat.STGATModel

num_classes: ${dataset.num_classes}
input_joints: ${dataset.input.num_joints}
input_features: ${dataset.input.num_features}

hidden_dim: 128
num_layers: 3
num_heads: 4
dropout: 0.2

graph:
  strategy: spatial
  learnable_adjacency: true
