from app.preprocessing.skeleton_preprocessor import SkeletonPreprocessor
from app.preprocessing.base_preprocessor import z_score_normalization, make_equal_length
from app.preprocessing.graph_builder import KINECT_EDGES, COCO_EDGES
